[env.production]
compatibility_flags = ["nodejs_compat"]

[env.preview]
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run pages:build"
cwd = "."

[site]
bucket = ".vercel/output/static" 